config/routes.rb
MyBook::Application.routes.draw do
  resources :profiles

  resources :posts

  resources :homes

  root :to => 'homes#index'
  match 'profiles/fetch/:id' => 'profiles#fetch', via: [:get]

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @post = Post.new
    @profile = Profile.first();
    @homes = Home.all
    @posts = Post.all(:order=>'created_at DESC')
    render layout: "application"
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
  #  @home = Home.new(home_params)
  #
  #  respond_to do |format|
  #    if @home.save
  #      format.html { redirect_to @home, notice: 'Home was successfully created.' }
  #      format.json { render action: 'show', status: :created, location: @home }
  #    else
  #      format.html { render action: 'new' }
  #      format.json { render json: @home.errors, status: :unprocessable_entity }
  #    end
  #  end
  end 

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params[:home]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all(:order=>'created_at ASC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all(:order =>'created_at DESC');
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { render :partial =>'layouts/post', :locals => { :posts => Post.all(:order =>'created_at DESC')}}
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render text: 'error' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:fetch, :show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  def fetch
    @profile = Profile.first()
    render :partial => 'layouts/profile_edit', :locals => {:profile => @profile}
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { render :partial => 'layouts/profile', :locals=> {:profile => @profile}}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:education, :hobbies, :birthday, :relationship)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
 <div class="well divfix" style="border-top:10px solid #0066FF">
      	<%= image_tag("facebook_2_1.jpg", :class=>"pull-left" , :style=>"display: inline-block; height:50px")%>

      	<form class="form-inline pull-right">
 			<input type="text" class="input-small" placeholder="Username">
  			<input type="password" class="input-small" placeholder="Password">
  			<button type="submit" class="btn">Sign in</button>
		</form>

      </div>

      <div class="well well-large divfix" style="border-top:10px solid #0099FF">
      	 <%= image_tag("flat-27716_640.png", :class=>"img-polaroid pull-left", :style=>"margin-right:30px; width:100px; display: inline-block;")%>
        <div>
        	<h4>
            Chatchanon Chinvetkitvanit 

            <button class="btn btn-mini pull-right" type="button" id="profile-edit-btn">Edit</button>
          </h4>
          <div id="profile-show">
              <%= render :partial => 'layouts/profile', :locals => { :profile => @profile} %>
          </div>

        </div>
      </div>

      <div class = "well divfix" style="border-top:10px solid #00CCFF">
              <%= render 'posts/form' %>
      		
      		<div class="pull-right">
            <ul class="nav nav-pills">
              <li>
              <div class="btn " href="#" style="margin-left:10px;"><i class="icon-star"></i> Like
              </div>
              </li>
              <li>
              <div class="input-prepend">
                <form style="margin-left:10px" class="form-small">
                  <span class="add-on"><i class="icon-envelope"></i></span>
                  <input class="span2 input-large" id="inputIcon" type="text" placeholder="Comment">
                </form>                           
              </div>
              </li>
            </ul>
              Note:Press ENTER for POST and SHIFT+ENTER for NEW LINE 
      		</div>
      </div>


      <div id="status-show">
      <%= render :partial => 'layouts/post', :locals => {:posts=>@posts } %>
      </div>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/_post.html.erb
<% posts.each do |post| %>

<% msgClass = cycle("pull-right","pull-left",:name => 'msg') %>
<% commentClass = cycle("pull-left","pull-right",:name =>"comment") %>

<div class = "well divfix"  style="border-top:10px solid #00CCFF">
      		<div class="<%= msgClass %>">
          <ul class="nav nav-pills">
              <li>
              <div class="btn " href="#" style="margin-left:10px;"><i class="icon-star"></i> Like
              </div>
              </li>
              <li>
              <div class="input-prepend">
                <form style="margin-left:10px" class="form-small">
                  <span class="add-on"><i class="icon-envelope"></i></span>
                  <input class="span2 input-large" id="inputIcon" type="text" placeholder="Comment">
                </form>                           
              </div>
              </li>
            </ul>
      		</div>
      		
      		<textarea class="status <%= commentClass %>" style="color: rgb(51, 51, 51);padding-top=10px; padding-left=10px" readonly><%= post.body %></textarea>
</div>

<% end %>

app/views/layouts/_profile.html.erb
              
<% if profile.present? %>
          <table id="profile-show-only" style="cellspacing:10px">
              <tr>
              <th class="span3">Education</th>
              <td><%= profile.education %></td>
              </tr> 
              
              <tr>
              <th>Hobbies</th>
              <td><%= profile.hobbies %></td>
              </tr>

              <tr>
              <th>Birthday</th>
              <td><%= profile.birthday %></td>
              </tr>

              <tr>
              <th>Relationship</th>
              <td><%= profile.relationship %></td>
              </tr>
          </table>
<% end %>

app/views/layouts/_profile_edit.html.erb
              
<% if profile.present? %>
<%= form_for(profile, :remote => true) do |f| %>
              
          <table id="profile-edit-form" style="cellspacing:10px">

              <tr>
              <th class="span3">Education</th>
              <td><%= f.text_field :education %></td>
              </tr> 
              
              <tr>
              <th>Hobbies</th>
              <td><%= f.text_field :hobbies %></td>
              </tr>

              <tr>
              <th>Birthday</th>
              <td><%= f.date_select :birthday, {:start_year => 1920, :order => [:day, :month, :year]}, {:class => "date-select"} %></td>
              </tr>

              <tr>
              <th>Relationship</th>
              <td><%= f.text_field :relationship %></td>
              </tr>
              <tr>
              <td class="text-center" colspan="2">
                <div class="pull-right">
                  <%= f.submit "Save", :class => "btn" %>
                  <button class="btn" id="profile-cancel-btn">Cancel</button>
                </div>
              </td>
              </tr>
            </table>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="mainbody">
<%= yield %>
<div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post,:remote => true do |f| %>
    <%= f.text_area :body, {:onkeyup =>"handlePostSubmit(event,this);", :onkeypress=>"return handlePostKey(event)", :class=>"status pull-left", :placeholder=>"What's in your mind", :required =>true } %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render :partial => 'layouts/post', :locals => {
  :posts => @posts
} %>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :hobbies %><br>
    <%= f.text_field :hobbies %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday, :start_year => 1920, :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br>
    <%= f.text_area :relationship %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Education</th>
      <th>Hobbies</th>
      <th>Birthday</th>
      <th>Relationship</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.education %></td>
        <td><%= profile.hobbies %></td>
        <td><%= profile.birthday %></td>
        <td><%= profile.relationship %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Education:</strong>
  <%= @profile.education %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @profile.hobbies %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile.birthday %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @profile.relationship %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>